package com.asia.frete.relatoriodefretev03;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class item implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Item")
   private java.lang.Integer nr_item;
   @org.kie.api.definition.type.Label(value = "Codigo da Taxa")
   private java.lang.Integer cd_taxa;
   @org.kie.api.definition.type.Label(value = "Valor da Taxa")
   private java.math.BigDecimal vl_taxa;
   @org.kie.api.definition.type.Label(value = "Cambio")
   private java.math.BigDecimal taxa_dolar;

   public item()
   {
   }

   public java.lang.Integer getNr_item()
   {
      return this.nr_item;
   }

   public void setNr_item(java.lang.Integer nr_item)
   {
      this.nr_item = nr_item;
   }

   public java.lang.Integer getCd_taxa()
   {
      return this.cd_taxa;
   }

   public void setCd_taxa(java.lang.Integer cd_taxa)
   {
      this.cd_taxa = cd_taxa;
   }

   public java.math.BigDecimal getVl_taxa()
   {
      return this.vl_taxa;
   }

   public void setVl_taxa(java.math.BigDecimal vl_taxa)
   {
      this.vl_taxa = vl_taxa;
   }

   public java.math.BigDecimal getTaxa_dolar()
   {
      return this.taxa_dolar;
   }

   public void setTaxa_dolar(java.math.BigDecimal taxa_dolar)
   {
      this.taxa_dolar = taxa_dolar;
   }

   public item(java.lang.Integer nr_item, java.lang.Integer cd_taxa,
         java.math.BigDecimal vl_taxa, java.math.BigDecimal taxa_dolar)
   {
      this.nr_item = nr_item;
      this.cd_taxa = cd_taxa;
      this.vl_taxa = vl_taxa;
      this.taxa_dolar = taxa_dolar;
   }

}