package com.asia.frete.relatoriodefretev03;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class containers implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "CONTAINERS_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(name = "CONTAINERS_ID_GENERATOR", sequenceName = "CONTAINERS_ID_SEQ")
   private java.lang.Long id;

   private int nr_fatura;

   private java.util.Date dt_eta;

   private java.lang.Boolean flag_fatura;

   public containers()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public int getNr_fatura()
   {
      return this.nr_fatura;
   }

   public void setNr_fatura(int nr_fatura)
   {
      this.nr_fatura = nr_fatura;
   }

   public java.util.Date getDt_eta()
   {
      return this.dt_eta;
   }

   public void setDt_eta(java.util.Date dt_eta)
   {
      this.dt_eta = dt_eta;
   }

   public java.lang.Boolean getFlag_fatura()
   {
      return this.flag_fatura;
   }

   public void setFlag_fatura(java.lang.Boolean flag_fatura)
   {
      this.flag_fatura = flag_fatura;
   }

   public containers(java.lang.Long id, int nr_fatura, java.util.Date dt_eta,
         java.lang.Boolean flag_fatura)
   {
      this.id = id;
      this.nr_fatura = nr_fatura;
      this.dt_eta = dt_eta;
      this.flag_fatura = flag_fatura;
   }

}