package com.asia.frete.relatoriodefretev03;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class corpo implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private com.asia.frete.relatoriodefretev03.roteiro roteiro;
   private com.asia.frete.relatoriodefretev03.pedido pedido;
   private com.asia.frete.relatoriodefretev03.cliente cliente;
   private com.asia.frete.relatoriodefretev03.item item;
   private java.lang.String link_para_ERP;
   private java.math.BigDecimal total_de_debitos;

   public corpo()
   {
   }

   public com.asia.frete.relatoriodefretev03.roteiro getRoteiro()
   {
      return this.roteiro;
   }

   public void setRoteiro(com.asia.frete.relatoriodefretev03.roteiro roteiro)
   {
      this.roteiro = roteiro;
   }

   public com.asia.frete.relatoriodefretev03.pedido getPedido()
   {
      return this.pedido;
   }

   public void setPedido(com.asia.frete.relatoriodefretev03.pedido pedido)
   {
      this.pedido = pedido;
   }

   public com.asia.frete.relatoriodefretev03.cliente getCliente()
   {
      return this.cliente;
   }

   public void setCliente(com.asia.frete.relatoriodefretev03.cliente cliente)
   {
      this.cliente = cliente;
   }

   public com.asia.frete.relatoriodefretev03.item getItem()
   {
      return this.item;
   }

   public void setItem(com.asia.frete.relatoriodefretev03.item item)
   {
      this.item = item;
   }

   public java.lang.String getLink_para_ERP()
   {
      return this.link_para_ERP;
   }

   public void setLink_para_ERP(java.lang.String link_para_ERP)
   {
      this.link_para_ERP = link_para_ERP;
   }

   public java.math.BigDecimal getTotal_de_debitos()
   {
      return this.total_de_debitos;
   }

   public void setTotal_de_debitos(java.math.BigDecimal total_de_debitos)
   {
      this.total_de_debitos = total_de_debitos;
   }

   public corpo(com.asia.frete.relatoriodefretev03.roteiro roteiro,
         com.asia.frete.relatoriodefretev03.pedido pedido,
         com.asia.frete.relatoriodefretev03.cliente cliente,
         com.asia.frete.relatoriodefretev03.item item,
         java.lang.String link_para_ERP, java.math.BigDecimal total_de_debitos)
   {
      this.roteiro = roteiro;
      this.pedido = pedido;
      this.cliente = cliente;
      this.item = item;
      this.link_para_ERP = link_para_ERP;
      this.total_de_debitos = total_de_debitos;
   }

}