package com.asia.frete.relatoriodefretev03;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class item implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public item() {
    }

}