package com.asia.frete.relatoriodefretev03;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class item implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "ITEM_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(name = "ITEM_ID_GENERATOR", sequenceName = "ITEM_ID_SEQ")
   private java.lang.Long id;

   private int nr_item;

   private java.util.Date dt_vencto;

   private java.math.BigDecimal vl_usr;

   private java.math.BigDecimal vl_real;

   private int cd_taxa;

   @org.kie.api.definition.type.Description("Cambio")
   private java.math.BigDecimal vl_taxa;

   private java.math.BigDecimal taxa_dolar;

   private java.lang.String tp_operacao;

   public item()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public int getNr_item()
   {
      return this.nr_item;
   }

   public void setNr_item(int nr_item)
   {
      this.nr_item = nr_item;
   }

   public java.util.Date getDt_vencto()
   {
      return this.dt_vencto;
   }

   public void setDt_vencto(java.util.Date dt_vencto)
   {
      this.dt_vencto = dt_vencto;
   }

   public java.math.BigDecimal getVl_usr()
   {
      return this.vl_usr;
   }

   public void setVl_usr(java.math.BigDecimal vl_usr)
   {
      this.vl_usr = vl_usr;
   }

   public java.math.BigDecimal getVl_real()
   {
      return this.vl_real;
   }

   public void setVl_real(java.math.BigDecimal vl_real)
   {
      this.vl_real = vl_real;
   }

   public int getCd_taxa()
   {
      return this.cd_taxa;
   }

   public void setCd_taxa(int cd_taxa)
   {
      this.cd_taxa = cd_taxa;
   }

   public java.math.BigDecimal getVl_taxa()
   {
      return this.vl_taxa;
   }

   public void setVl_taxa(java.math.BigDecimal vl_taxa)
   {
      this.vl_taxa = vl_taxa;
   }

   public java.math.BigDecimal getTaxa_dolar()
   {
      return this.taxa_dolar;
   }

   public void setTaxa_dolar(java.math.BigDecimal taxa_dolar)
   {
      this.taxa_dolar = taxa_dolar;
   }

   public java.lang.String getTp_operacao()
   {
      return this.tp_operacao;
   }

   public void setTp_operacao(java.lang.String tp_operacao)
   {
      this.tp_operacao = tp_operacao;
   }

   public item(java.lang.Long id, int nr_item, java.util.Date dt_vencto,
         java.math.BigDecimal vl_usr, java.math.BigDecimal vl_real, int cd_taxa,
         java.math.BigDecimal vl_taxa, java.math.BigDecimal taxa_dolar,
         java.lang.String tp_operacao)
   {
      this.id = id;
      this.nr_item = nr_item;
      this.dt_vencto = dt_vencto;
      this.vl_usr = vl_usr;
      this.vl_real = vl_real;
      this.cd_taxa = cd_taxa;
      this.vl_taxa = vl_taxa;
      this.taxa_dolar = taxa_dolar;
      this.tp_operacao = tp_operacao;
   }

}