package com.asia.frete.relatoriodefretev03;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class pedido implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private int filial_operac;

   private int nr_pedido;

   public pedido()
   {
   }

   public int getFilial_operac()
   {
      return this.filial_operac;
   }

   public void setFilial_operac(int filial_operac)
   {
      this.filial_operac = filial_operac;
   }

   public int getNr_pedido()
   {
      return this.nr_pedido;
   }

   public void setNr_pedido(int nr_pedido)
   {
      this.nr_pedido = nr_pedido;
   }

   public pedido(int filial_operac, int nr_pedido)
   {
      this.filial_operac = filial_operac;
      this.nr_pedido = nr_pedido;
   }

}