package com.asia.frete.relatoriodefretev03;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class roteiro implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public roteiro() {
    }

}