package com.asia.frete.relatoriodefretev03;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class tbl_item implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @javax.persistence.GeneratedValue(generator = "TBL_ITEM_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
    @javax.persistence.Id
    @javax.persistence.SequenceGenerator(name = "TBL_ITEM_ID_GENERATOR", sequenceName = "TBL_ITEM_ID_SEQ")
    private java.lang.Long id;

    public tbl_item() {
    }
    
    public tbl_item(java.lang.Long id) {
        this.id = id;
    }

    public java.lang.Long getId() {
        return this.id;
    }
    
    public void setId(java.lang.Long id) {
        this.id = id;
    }

}