package asiashipping;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class base implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "empresa")
   private java.lang.String empresa;
   @org.kie.api.definition.type.Label(value = "pedido")
   private java.lang.String pedido;
   @org.kie.api.definition.type.Label(value = "ano")
   private java.lang.Integer ano;
   @org.kie.api.definition.type.Label(value = "Roteiro")
   private java.lang.String roteiro;
   @org.kie.api.definition.type.Label(value = "Cliente")
   private java.lang.String cliente;
   @org.kie.api.definition.type.Label(value = "Codigo de Importacao")
   private java.lang.String cd_importacao;
   @org.kie.api.definition.type.Label(value = "Cliente Follow")
   private java.lang.String cliente_follow;
   @org.kie.api.definition.type.Label(value = "Filial")
   private java.lang.String filial;
   @org.kie.api.definition.type.Label(value = "Vendedo/CS")
   private java.lang.String vendedor_cs;
   @org.kie.api.definition.type.Label(value = "Faturado")
   private boolean faturado;
   @org.kie.api.definition.type.Label(value = "Data ETA")
   private java.util.Date data_eta;
   @org.kie.api.definition.type.Label(value = "Data de Vencimento")
   private java.util.Date dt_vencimento;
   @org.kie.api.definition.type.Label(value = "Dias de Atraso")
   private java.util.Date dias_atraso;
   @org.kie.api.definition.type.Label(value = "Taxa")
   private java.math.BigDecimal taxa;
   @org.kie.api.definition.type.Label(value = "Valor")
   private java.math.BigDecimal valor;
   @org.kie.api.definition.type.Label(value = "Cambio")
   private java.math.BigDecimal cambio;

   public base()
   {
   }

   public java.lang.String getEmpresa()
   {
      return this.empresa;
   }

   public void setEmpresa(java.lang.String empresa)
   {
      this.empresa = empresa;
   }

   public java.lang.String getPedido()
   {
      return this.pedido;
   }

   public void setPedido(java.lang.String pedido)
   {
      this.pedido = pedido;
   }

   public java.lang.Integer getAno()
   {
      return this.ano;
   }

   public void setAno(java.lang.Integer ano)
   {
      this.ano = ano;
   }

   public java.lang.String getRoteiro()
   {
      return this.roteiro;
   }

   public void setRoteiro(java.lang.String roteiro)
   {
      this.roteiro = roteiro;
   }

   public java.lang.String getCliente()
   {
      return this.cliente;
   }

   public void setCliente(java.lang.String cliente)
   {
      this.cliente = cliente;
   }

   public java.lang.String getCd_importacao()
   {
      return this.cd_importacao;
   }

   public void setCd_importacao(java.lang.String cd_importacao)
   {
      this.cd_importacao = cd_importacao;
   }

   public java.lang.String getCliente_follow()
   {
      return this.cliente_follow;
   }

   public void setCliente_follow(java.lang.String cliente_follow)
   {
      this.cliente_follow = cliente_follow;
   }

   public java.lang.String getFilial()
   {
      return this.filial;
   }

   public void setFilial(java.lang.String filial)
   {
      this.filial = filial;
   }

   public java.lang.String getVendedor_cs()
   {
      return this.vendedor_cs;
   }

   public void setVendedor_cs(java.lang.String vendedor_cs)
   {
      this.vendedor_cs = vendedor_cs;
   }

   public boolean isFaturado()
   {
      return this.faturado;
   }

   public void setFaturado(boolean faturado)
   {
      this.faturado = faturado;
   }

   public java.util.Date getData_eta()
   {
      return this.data_eta;
   }

   public void setData_eta(java.util.Date data_eta)
   {
      this.data_eta = data_eta;
   }

   public java.util.Date getDt_vencimento()
   {
      return this.dt_vencimento;
   }

   public void setDt_vencimento(java.util.Date dt_vencimento)
   {
      this.dt_vencimento = dt_vencimento;
   }

   public java.util.Date getDias_atraso()
   {
      return this.dias_atraso;
   }

   public void setDias_atraso(java.util.Date dias_atraso)
   {
      this.dias_atraso = dias_atraso;
   }

   public java.math.BigDecimal getTaxa()
   {
      return this.taxa;
   }

   public void setTaxa(java.math.BigDecimal taxa)
   {
      this.taxa = taxa;
   }

   public java.math.BigDecimal getValor()
   {
      return this.valor;
   }

   public void setValor(java.math.BigDecimal valor)
   {
      this.valor = valor;
   }

   public java.math.BigDecimal getCambio()
   {
      return this.cambio;
   }

   public void setCambio(java.math.BigDecimal cambio)
   {
      this.cambio = cambio;
   }

   public base(java.lang.String empresa, java.lang.String pedido,
         java.lang.Integer ano, java.lang.String roteiro,
         java.lang.String cliente, java.lang.String cd_importacao,
         java.lang.String cliente_follow, java.lang.String filial,
         java.lang.String vendedor_cs, boolean faturado,
         java.util.Date data_eta, java.util.Date dt_vencimento,
         java.util.Date dias_atraso, java.math.BigDecimal taxa,
         java.math.BigDecimal valor, java.math.BigDecimal cambio)
   {
      this.empresa = empresa;
      this.pedido = pedido;
      this.ano = ano;
      this.roteiro = roteiro;
      this.cliente = cliente;
      this.cd_importacao = cd_importacao;
      this.cliente_follow = cliente_follow;
      this.filial = filial;
      this.vendedor_cs = vendedor_cs;
      this.faturado = faturado;
      this.data_eta = data_eta;
      this.dt_vencimento = dt_vencimento;
      this.dias_atraso = dias_atraso;
      this.taxa = taxa;
      this.valor = valor;
      this.cambio = cambio;
   }

}